### ISSUE TITLE
Compile Error, even after modifying boarddefs.h 

### ISSUE THREAD

**Issue by 68gt500** [Grrarth/Arduino_ESP32_IRRemote_Mods#1]
ESP32 Doit Devkit V1
IDE: 1.8.8
Sketch: IRrecDump.ini

Error Log:
In file included from E:\Eigene Dateien\Eigene Dateien\Arduino\libraries\Arduino-IRremote\IRremoteInt.h:111:0,

                 from E:\Eigene Dateien\Eigene Dateien\Arduino\libraries\Arduino-IRremote\IRremote.h:24,

                 from E:\Eigene Dateien\Eigene Dateien\Arduino\libraries\Arduino-IRremote\ir_Mitsubishi.cpp:1:

E:\Eigene Dateien\Eigene Dateien\Arduino\libraries\Arduino-IRremote\boarddefs.h:94:32: warning: extra tokens at end of #undef directive

 #       undef SENDING_SUPPORTED#

**Comment by Grrarth** [comment]
I have modified the code to include how it "should" be but that didn't work for me which is why I used the constant declaration instead. It worked for me or I wouldn't embarrass myself with this repository. Now both lines are there to choose from. If that doesn't work then maybe try another library. Cheers.
After rereading the issue I have also corrected the trailing hash character that you pointed out. I don't remember putting it there so thanks for mentioning it.
